# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
      - README.adoc
      - .gitignore

pool:
  vmImage: 'ubuntu-latest'
  demands:
    - maven

variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

steps:
- task: Cache@2
  displayName: Cache Maven local repo
  inputs:
    key: 'maven | "$(Agent.OS)" | **/pom.xml'
    restoreKeys: |
       maven | "$(Agent.OS)"
       maven
    path: $(MAVEN_CACHE_FOLDER)
  
- task: Maven@3
  displayName: 'build, test, code coverage'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    goals: 'package'

- task: CopyFiles@2
  displayName: 'Copy Azure artifacts for maven deploy to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)/target'
    Contents: '**/*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  condition: succeeded()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: application'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: application
  condition: succeeded()

- task: Maven@3
  displayName: 'deploy'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    mavenAuthenticateFeed: true
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    goals: 'deploy'
  condition: succeeded()